<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cookie_data_privacy"
 *
 * Auto generated by Extension Builder 2018-05-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Cookie Privacy & Data Privacy (DSGVO)',
    'description' => 'Cookie Privacy: The Cookie Law is a piece of privacy legislation that requires websites to get consent from visitors to store or retrieve any information on a computer, smartphone or tablet. Data Privacy: Datenschutz-Grundverordnung (DSGVO), englisch General Data Protection Regulation (GDPR) is a regulation of the European Union , which standardises the rules on the processing of personal data by private companies and public authorities across the EU. DSGVO is directly applicable from 25 May 2018.',
    'category' => 'services',
    'author' => 'Ghanshyam B. Gohel',
    'author_email' => 'ghanshyam.typo3developer@gmail.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '10.4.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.27-10.4.99',
            'vhs' => '5.0.0-6.1.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
